apiVersion: apps/v1
kind: Deployment
metadata:
  name: azureblobapp-deployment
spec:
  selector:
    matchLabels:
      app: azureblobapp
  template:
    metadata:
      labels:
        app: azureblobapp
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: azureblobapp-serviceaccount
      containers:
        - name: azureblobapp
          image: ordercontainerregistry.azurecr.io/azureblobapp:1.0.1
          ports:
            - containerPort: 5002
          env:
            - name: BlobSettings__Url
              value: https://myorderkeyvault.vault.azure.net/
           
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
            requests:
              memory: "128Mi"
              cpu: "150m"
      restartPolicy: Always
  

